version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server
      - redis
    command: sh -c './wait-for-it.sh -t 0 mysql_server:3306 -- npm run start:dev'

  redis:
    image: redis
    expose:
      - "6379"
    # ports:
    #   - '6379:6379'

  mysql_server:
    image: mysql:8.1
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
