version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    depends_on:
      - mysql_server
      - redis
    command: sh -c './wait-for-it.sh -t 0 mysql_server:3306 -- npm run start'

  redis:
    image: redis
    expose:
      - "6379"

  mysql_server:
    image: mysql:8.1
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
